### ISSUE TITLE
Cayenne Lpp Size, wanted more than 51 bytes to Send to LoRa Gateway.

### ISSUE THREAD

**Issue by aylashiv** [ElectronicCats/CayenneLPP#53]
CayenneLPP::CayenneLPP(uint8_t size) : _maxsize(size) , My payload requirement, (which contains multiple sensor elements), the payload size has been grown more than 51 bytes, i'm unable to send the data to LoRa Gateway. Can you suggest any method to Solve it.

**Comment by xoseperez** [comment]
You have different options.

1) Increase your transmission speed so 51 bytes is no longer you limit, of course this will only work if you are in range of a gateway but in general sending at SF12 is something to avoid. Try set it to SF9 and see if you packet is still received.
2) Use a diffrent, custom encoding. CayenneLPP adds some metadata to the message to identify the channel and the data type. You can reduce significantly the payload size doing your own encoding. You will of course need your own decoder at the LNS...
3) Split the message in submessages. You will of course reduce the frequency update for each individual measurement.

I will definitely work on 1 above since it will improve many metrics (ToA, spectrum polution, battery consumption, payload size capacity,...) and maybe move to 2 if I still need to reduce payload size.

**Comment by aylashiv** [comment]
@xoseperez That is impressive, sure will try out the methods you have suggested. Thanks a lot :)
